services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db1
    environment:
      MYSQL_ROOT_PASSWORD: praveen1357M@
      MYSQL_DATABASE: albumly
      MYSQL_USER: root
      MYSQL_PASSWORD: praveen1357M@
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  spring-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db1:3306/albumly
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: praveen1357M@
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend

  react-frontend:
    build:
      context: ./S02L03 - Making template changes
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - spring-backend
    networks:
      - backend
    command: npm start

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
